import os
import struct, re, glob


# 3D MATHS UTILITY FUNCTIONS
def vector_sum(v1 : list[float], v2 : list[float]) -> list[float]:
    """Sum two vectors which are actually lists and not NumPy vectors cause my code is built different
        TODO: per favore ti supplico me del futuro usa NumPy
    Args:
        v1: vector 1
        v2: vector 2
    Returns:
        sum of the vectors
    """
    return [ v1[0] + v2[0], v1[1] + v2[1], v1[2] + v2[2] ]

def vector_sum3(v1 : list[float], v2 : list[float], v3 : list[float]) -> list[float]:
    """Sum three vectors

    Args:
        v1: vector 1
        v2: vector 2
        v3: vector 3
    Returns:
        sum of the vectors
    """
    return [ v1[0] + v2[0] + v3[0], v1[1] + v2[1] + v3[1], v1[2] + v2[2] + v3[2]]

def vector_sub(v1 : list[float], v2 : list[float]) -> list[float]:
    return [ v1[0] - v2[0], v1[1] - v2[1], v1[2] - v2[2] ]

def dot_product(v1 : list[float], v2 : list[float]) -> list[float]:
    result = 0
    for i in range( len(v1) ):
        result += v1[i] * v2[i]
    return result

# TODO: remove all the methods above and use some library intead.

def find_plane(v1 : list[float], v2 : list[float]) -> list[float]:
    """Find the plane generated by vectors v1 and v2

    find the plane the vectors v1 and v2 belong to
    return: [ a, b, c ], which represents the normal of the plane
    the equation of the plane is ax + by + cz = 0

    Args:
        v1: vector 1
        v2: vector 2
    Returns:
        list of three floats. it represents the normal of the plane
    """

    a = det2( [ [ v1[1], v1[2] ],
                [ v2[1], v2[2] ] ] )
    
    b = det2( [ [ v1[0], v1[2] ],
                [ v2[0], v2[2] ] ] ) * -1
    
    c = det2( [ [ v1[0], v1[1] ],
                [ v2[0], v2[1] ] ] )
    
    return [ a, b, c ]




def det2(m : list[list[float]]) -> float:
    """Find the determinant of a 2x2 matrix

    Args:
        m: 2x2 matrix
    Returns:
        determinant of the matrix
    """
    return (m[0][0] * m[1][1]) - (m[0][1] * m[1][0])




# This function checks the vertex normals of a tri to determine on which side that tri should face.
# If the triangle vertices are clockwise, it makes them counterclockwise. Otherwise does nothing.
def adjust_normals_for_dae(tri : list[int], geometry):  # TODO: move this into the Model3d class
    """Correct triangles for dae format

    Edits triangles so that their normal points in the right direction when converting from rlg to dae.
    In particular, check the vertex normals of a tri to determine on which side that tri should face.
    If the triangle vertices are clockwise, it makes them counterclockwise. Otherwise does nothing.

    Args:
        tri: triangle. is altered during the execution
        geometry: TODO: is this Mesh? I think so
    """
    # look at the vertex normals to determine which side the tri is facing (this is how it works in .rlg files)
    vertices = geometry.vertices
    index0 = tri.indices[0]
    index1 = tri.indices[1]
    index2 = tri.indices[2]

    # sum the normals of the vertices. In the rlg format, the triagle faces towards this point
    # (this is not actually the normal, just a random point on the same side as the normal)
    tri_normal_thing = vector_sum3( vertices[ index0 ].normal, vertices[ index1 ].normal, vertices[ index2 ].normal )

    # make a matrix of the positions of the triangle's vertices
    tri_positions = [ [ vertices[ index0 ].position[0], vertices[ index0 ].position[1], vertices[ index0 ].position[2] ],
                      [ vertices[ index1 ].position[0], vertices[ index1 ].position[1], vertices[ index1 ].position[2] ],
                      [ vertices[ index2 ].position[0], vertices[ index2 ].position[1], vertices[ index2 ].position[2] ] ]
    
    # shift the tri in a way so that the first vertex is on the origin
    tri_positions_on_origin = [ vector_sub( tri_positions[0], tri_positions[0] ),
                                vector_sub( tri_positions[1], tri_positions[0] ),
                                vector_sub( tri_positions[2], tri_positions[0] ) ]

    # find the counterclockwise normal
    dae_normal = find_plane( tri_positions_on_origin[1], tri_positions_on_origin[2] )

    # determine whether the vertex normal sum is on the counterclockwise side or not.
    # use dot product for this. If the result is negative they're on opposite sides
    # in that case, it would be on the clockwise side, so swap two of the indices to make it counterclockwise
    if dot_product( dae_normal, tri_normal_thing ) < 0:
        # swap two indices
        tmp = tri.indices[0]
        tri.indices[0] = tri.indices[1]
        tri.indices[1] = tmp




# FILE UTILITY FUNCTIONS
def get_all_filenames_of_specified_extension(dir_path : str, extension : str) -> list[str]:
    """Get filenames of extension in dir_path directory

    Args:
        dir_path: path of the directory to look into
        extension: extension to look for
    Return:
        list of filenames
    """
    filenames_r = glob.glob( "./{0}*{1}".format( dir_path, extension )  )
    filenames = []
    for i in filenames_r:
        file = re.split("\\\\", i)[1]
        print(file)
        filenames.append(file)
    return filenames




def get_file_extension(filepath):
    return filepath.split( '.' )[ -1 ]




def check_daepath(rlgpath : str) -> str:
    """Convert rlg filepath to a dae filepath

    Args:
        rlgpath: path of the rlg file
    Return:
        rlgpath + '.dae'
    """
    daepath = rlgpath + '.dae'
    if not os.path.isfile(daepath):
        return None
    return daepath




def check_rlgpath(daepath : str) -> str:
    """Convert dae filepath to a rlg filepath

    Args:
        daepath: path of the dae file
    Return:
        daepath - '.dae'
    """
    rlgpath = daepath[ :-4 ]
    if not os.path.isfile( rlgpath ):
        return None
    return rlgpath




# DATA TYPE UTILITY FUNCTIONS
def byte_hex_str(bytes : bytes) -> str:
    """Convert a bytes object into an hex string represented by ascii characters

    For example:  b'\x06\x07\xef\x0d' becomes '0607ef0d'

    Args:
        bytes: bytes object
    Return:
        string of ascii chars that represent the given bytes in hex
    """
    string = ""
    for i in bytes:
        string += byte_hex(i)
    return string




def byte_hex(byte : bytes) -> str:  # TODO: maybe it returns int?? Double check pls
    """Convert a bytes object of len 1 into a string of len 1

    For example:  b'\xc8' becomes 'c8'

    Args:
        bytes: bytes object
    Return:
        string of ascii chars that represent the given bytes in hex
    """
    upper4 = (byte & 0xf0) >> 4 
    lower4 = byte & 0x0f
    chars = ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']
    return (chars[upper4] + chars[lower4])




def bytes_to_float(bytes : bytes) -> float:
    """Convert a bytes object into a IEEE-754 single precision floating
    point number

    For example:  b'\\x3f\\x80\\x00\\x00' becomes 1.0

    Args:
        bytes: bytes object
    Return:
        float number
    """
    # TODO: should there be a test for the bytes length to be 4?
    return struct.unpack( '!f', bytes )[0]




def float_to_bytes4(number : float) -> bytes:
    """Convert a IEEE-754 standard floating point number into a bytes object of len 4

    For example: 1.0 becomes b'\x3f\x80\x00\x00'

    Args:
        number: float number
    Return:
        bytes object of length 4
    """
    hexstr = hex(struct.unpack('<I', struct.pack( '<f', number ))[0])
    if hexstr != "0x0":
        return bytes.fromhex( hexstr[2:] )
    return b'\x00\x00\x00\x00'
    



# TODO: maybe change name to the two following methods?
def float_to_bytes2(float : float) -> bytes:
    """Convert a IEEE-754 standard floating point number into a bytes object of len 2

    This function takes a float value as input.
    It then multiplies this float by 1024. Then it casts it to a bytes object with the length of 2.
    That's how uv coordinates are represented in .rlg files.

    Args:
        float: float number
    Returns:
        bytes object of length 2
    """
    integer = int(float * 1024)
    return integer.to_bytes(2, 'big', signed=True)




def float_to_bytes1(float : float) -> bytes:
    """Convert a IEEE-754 standard floating point number into a bytes object of len 1

    This function takes a float value as input.
    It then multiplies this float by 255. Then it casts it to a bytes object with the length of 1.
    That's how normals are sometimes represented in .rlg files.

    Args:
        float: float number
    Returns:
        bytes object of length 1
    """
    integer = int(float * 255)
    return integer.to_bytes(1, 'big', signed=True)